// Generated by CoffeeScript 1.4.0
var build, compile, convert, filename, fill, fs, parse, path, redo, source_file;

build = require('./build').build;

parse = require('./parse').parse;

convert = require('she').convert;

fs = require('fs');

source_file = '../source/source.sp';

fill = function(item) {
  var _ref;
  return !((_ref = item.trim()) === ';' || _ref === '');
};

compile = function(file) {
  var array, code;
  array = parse(convert(file));
  return code = build(array);
};

path = require('path');

filename = path.join(process.env.PWD, process.argv[2]);

if ((path.extname(filename)) !== '.sp') {
  throw new Error('not .sp file');
} else {
  (redo = function() {
    var file;
    file = fs.readFileSync(filename, 'utf8');
    return console.log(compile(file));
  })();
}
